repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
    - id: mypy

-   repo: http://gitlab.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      language_version: python3.8
      additional_dependencies: 
       - flake8-docstrings
       - flake8-eradicate
       - flake8-fixme
       - flake8-rst
       - flake8-mutable
